# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            StickyData
tagline:          'building better data teams'
description:      'This site collects my thinking, writing and doing, and the best of what I find elsewhere.'
url:              http://stickydata.co
baseurl:          /

author:
  name:           'Shaun McGirr'
  url:            https://twitter.com/shaunmcgirr

paginate:         5

# Custom vars

